# Generated by Django 3.1.4 on 2020-12-24 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201223_2331'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='word',
            new_name='words',
        ),
    ]
